version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run: 
          name: get-ip smoke test 
          command: dagger call --progress=plain -m get-ip run
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)