version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.17
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run: 
          command: env 
      - run:
          name: show dagger version 
          command: dagger version
      - run: 
          name: get-ip smoke test 
          command: dagger call --progress=plain -m get-ip run
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)

  toot:
    docker:
      - image: cimg/go:1.17
    resource_class: medium
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run: 
          name: send toot
          command: dagger call toot \
            --server="https://hachyderm.io" \
            --client-id="-3UXCeKKYu3U1z2ZANnONS-Artc-WbMuMRKOuSvzuiI" \
            --client-secret=env:MASTODON_CLIENT_SECRET \
            --access-token=env:MASTODON_ACCESS_TOKEN \
            --msg="I just published a new version of a Dagger module, $CIRCLE_TAG, check it out! https://github.com/levlaz/daggerverse" \
            --visibility=direct

workflows:
    build:
        jobs:
            - build
    notify:
        jobs:
            - toot:
                filters:
                    tags:
                        only: /^v.*/